import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Providers";
// import { AnimatePresence } from "framer-motion";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { ThemeProvider } from "./components/themeProvider";
import QueryProviders from "@/lib/ReactQuery/QueryProvider";
import GlobalNav from "./components/globalNavBar";
import { GlobalContextProvider } from "@/context/Global/GlobalContext";
import { UserInfoContextProvider } from "@/context/users/userInfoContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
          <html lang="en">
            <body className={``} >
              <Providers>
                  <QueryProviders>
                    <GlobalContextProvider>
                      <UserInfoContextProvider>
                      {/* // <AnimatePresence mode="wait"> Optional mode prop */}
                      <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                        >
                        <GlobalNav/>
                        {children}
                        </ThemeProvider>
                        {/* // </AnimatePresence> */}
                        </UserInfoContextProvider>
                      </GlobalContextProvider>
                  <ReactQueryDevtools initialIsOpen={false} />
                </QueryProviders>
              </Providers>
            </body>
          </html>
  );
}
